New Method added
Kaholo/kaholo-plugin-jira pull request #15
Opened 2022-02-08 07:29 UTC by rais24

Get assignee method added

2022-02-08 07:32 UTC, rais24 commented
Pull request created with new code format.

2022-05-18 09:24 UTC, soniasok approved these changes
.

2022-05-24 10:40 UTC, graddaniel requested changes
Before implementing requested changes please add lint in a separate commit.
You can get the `.eslintrc.js`, `.gitignore`s and `npm run lint` command from the template.
https://github.com/Kaholo/kaholo-plugin-template

2022-05-24 10:40 UTC, graddaniel commented on helpers.js
> +    const usersgroup = await client.getUsersInGroup(params.group);
Please use camel case for variables' names

2022-05-24 10:40 UTC, graddaniel commented on helpers.js
> +    listAssigneedetails
camel case

2022-05-24 10:40 UTC, graddaniel commented on config.json
> +  "version": "2.2.4",
You're adding a new method. It should be `2.3.0` then.

2022-05-24 10:40 UTC, graddaniel commented on app.js
> +  listAssigneedetails:stripAction(helpers.listAssigneedetails),
camel case

2022-05-24 10:40 UTC, graddaniel commented on autocomplete.js
> +   // let queryTime = new Date().toISOString().split("T")[0];
Delete this line of code if we don't use it anymore.

2022-05-24 10:40 UTC, graddaniel commented on autocomplete.js
> +       // queryTime = new Date(query).toISOString().split("T")[0];
Delete this line of code if we don't use it anymore.

2022-05-24 10:40 UTC, graddaniel commented on autocomplete.js
> +    queryTime= (((date.getMonth() > 8) ? (date.getMonth() + 1) : ('0' + (date.getMonth() + 1))) + '/' + ((date.getDate() > 9) ? date.getDate() : ('0' + date.getDate())) + '/' + date.getFullYear());
```suggestion
    const stringFormattedMonth = `${date.getMonth() > 8 ? "" : "0"}${date.getMonth() + 1}`;
    const stringFormattedDay = `${date.getDate() > 9 ? "" : "0"}${date.getDate() + 1}`;
    const queryTime= `${stringFormattedMonth}/${stringFormattedDay}/${date.getFullYear()}`;
```

We appreciate high intelectual skills of people who are able to understand such complex structures in a blink of an eye, but let's save their (and the less intelligent ones) brain computing power for serious engineering problems, and let's simplify common solutions.

2022-05-24 10:40 UTC, graddaniel commented on autocomplete.js
>      if (query){
Instead of computing the `queryTime` first, and then recomputing it if `query` is truthy, let's conditionally select the date we base on and then compute `queryTime` reusing that date, eg:
`
const date = query ? new Date(query) : new Date();
const queryTime = ...
`

2022-05-24 10:40 UTC, graddaniel commented on config.json
> +      "name": "listAssigneedetails",
camel case

2022-05-24 10:40 UTC, graddaniel commented on config.json
> +          "name": "group",
If it contains Group Name, let's name it `groupName` then. It won't hurt, and will be easier to understand the code.

2022-05-24 10:40 UTC, graddaniel commented on autocomplete.js
> +        queryTime= (((date.getMonth() > 8) ? (date.getMonth() + 1) : ('0' + (date.getMonth() + 1))) + '/' + ((date.getDate() > 9) ? date.getDate() : ('0' + date.getDate())) + '/' + date.getFullYear()
Same here as in the suggested change above, however this will not be necessary once the query time is computed once only.

2022-05-24 10:40 UTC, graddaniel commented on autocomplete.js
> +
Why so many new lines?

2022-05-24 10:40 UTC, graddaniel commented on helpers.js
> +
Why 3 new lines?

2022-05-24 10:40 UTC, graddaniel commented on helpers.js
> +    let jql = "";
What's that magic abbreviation? Please use a descriptive name.

2022-05-24 10:40 UTC, graddaniel commented on helpers.js
> +        parsers.array(params.fields || ["created", "description", "summary", "status", "priority","assignee","reporter","project"]);
Please store the default `fields` array in a constant at top of this file.

2022-07-08 08:48 UTC, graddaniel commented
This has been taken care of in https://github.com/Kaholo/kaholo-plugin-jira/pull/16

2022-07-08 08:48 UTC, closed without merging