KP-741 [Jira] Please resolve outstanding PR, flatten, eslint
Kaholo/kaholo-plugin-jira pull request #16
Opened 2022-06-30 14:17 UTC by xkcm

[**KP-741 in Jira**](https://kaholo.atlassian.net/browse/KP-741)

2022-07-01 07:40 UTC, graddaniel requested changes

2022-07-01 07:40 UTC, graddaniel commented on jira-list-functions.js
> +  return usersResult.users.items;
This is will throw a `TypeError` if `users` property is empty.

2022-07-01 07:40 UTC, graddaniel commented on jira-list-functions.js
> +    const startDateFormatted = new Date(startDate).toISOString().split("T")[0];
Every such call in this file could go to `helpers.js`, which would help if we decided to alter the date parsing in future`;

2022-07-01 09:12 UTC, graddaniel approved these changes

2022-07-05 12:15 UTC, kenskyfish approved these changes
testing, working well.

2022-07-05 13:00 UTC, merged